#!/usr/bin/env python

import getopt
import sys

from libcloud.resource.lb.base import LB, LBNode

from lctools.lc import get_lc
from lctools.printer import Printer


def usage(prog):
    sys.stdout.write(("%s -n <name> [-p <profile> ]"
        " [ -P <port> ] addr1:port1 add2:port2 ...\n\n") % prog)

if __name__ == "__main__":
    profile = "default"
    port = 80
    name = None

    try:
        opts, args = getopt.getopt(sys.argv[1:], "p:P:n:")
    except getopt.GetoptError, err:
        sys.stderr.write("%s\n" % str(err))
        sys.exit(1)

    for o, a in opts:
        if o == "-p":
            profile = a
        elif o == "-P":
            port = a
        elif o == "-n":
            name = a

    conn = get_lc(profile, resource='lb')

    nodes = []

    for node in args:
        addr, port = node.split(":")
        nodes.append(LBNode(None, addr, port))

    if name is None or len(nodes) == 0:
        usage(sys.argv[0])
        sys.exit(1)

    balancer = conn.create_balancer(name=name, port=port, nodes=nodes)
    print balancer
