#!/usr/bin/env python

import getopt
import sys

from libcloud.loadbalancer.base import LoadBalancer, Member

from lctools.lc import get_lc
from lctools.printer import Printer


def usage(prog):
    sys.stdout.write(("%s -i <id> [-p <profile> ]\n\n") % prog)

if __name__ == "__main__":
    profile = "default"
    lb_id = None

    try:
        opts, args = getopt.getopt(sys.argv[1:], "p:i:")
    except getopt.GetoptError, err:
        sys.stderr.write("%s\n" % str(err))
        sys.exit(1)

    for o, a in opts:
        if o == "-p":
            profile = a
        elif o == "-i":
            lb_id = a

    conn = get_lc(profile, resource='loadbalancer')

    nodes = []

    if lb_id is None:
        usage(sys.argv[0])
        sys.exit(1)

    balancer = LoadBalancer(lb_id, None, None, None, None, None)
    members = conn.balancer_list_members(balancer)
    for member in members:
        print member
