#!/usr/bin/env python

import getopt
import sys

from lctools.lc import get_lc
from lctools.printer import Printer
from lctools.shortcuts import get_node_or_fail, print_error_and_exit

def usage(progname):
    sys.stdout.write("%s -i <node_id> -n <image_name>\n\n" % progname)

if __name__ == "__main__":
    profile = 'default'
    node_id = None

    try:
        opts, args = getopt.getopt(sys.argv[1:], "i:n:")
    except getopt.GetoptError, err:
        sys.stderr.write("%s\n" % str(err))
        sys.exit(1)

    for o, a in opts:
        if o == "-i":
            node_id = a
        if o == "-n":
            name = a

    if node_id is None or name is None:
        usage(sys.argv[0])
        sys.exit(1)

    conn = get_lc(profile)

    node = get_node_or_fail(conn, node_id, print_error_and_exit, 
            ("Error: cannot find node with id '%s'." % node_id,))

    Printer.do(conn.ex_save_image(node, name))
